mohsun_struct_133
BranchAndLink/GoLangFastPaced pull request #184
Opened 2023-09-05 13:27 UTC by Mohsun88

#133

2023-09-05 13:31 UTC, quickwritereader commented
@Mohsun88 struct embedding aid numune yoxdur

2023-09-05 13:33 UTC, quickwritereader commented
reflect den az istifade ele. %T var. 
reflection movzusunda edersen

2023-09-05 13:35 UTC, quickwritereader requested changes
struct embedding.  
struct tag field.  
do not use reflect that much

2023-09-06 07:37 UTC, Mohsun88 commented
@quickwritereader embedding e aid numune elave etdim. 
Tag var idi eslinde, json_string olan hisseye baxarsan , newEmployee struct i uzerindedi. 
reflection evezine bezi yerlerde %T istifade eledim, baxarsan zehmet olmasa.

2023-09-06 07:44 UTC, quickwritereader commented
Exi embedded yoxdur

2023-09-06 07:45 UTC, quickwritereader commented
Bir zehmet bura atarsan neyi embedded sayirsan, duzelish edim. 
He tag fieldi gördüm

2023-09-06 07:45 UTC, quickwritereader commented
go fmt . Chagir ki format getsin fayl

2023-09-06 09:51 UTC, quickwritereader approved these changes

2023-09-06 09:51 UTC, merged